[package]
name = "bodycalc"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "^0.14.0"
relm = "^0.22.0"
relm-derive = "^0.22.0"
glib = "^0.14.0"
rt-format = "^0.2"